module Graphics.XHB.Monad.Internal.Instances () where
import Graphics.XHB.Monad.Internal.Instances.BigRequests
import Graphics.XHB.Monad.Internal.Instances.Composite
import Graphics.XHB.Monad.Internal.Instances.Damage
import Graphics.XHB.Monad.Internal.Instances.DPMS
import Graphics.XHB.Monad.Internal.Instances.DRI2
import Graphics.XHB.Monad.Internal.Instances.Glx
import Graphics.XHB.Monad.Internal.Instances.RandR
import Graphics.XHB.Monad.Internal.Instances.Record
import Graphics.XHB.Monad.Internal.Instances.Render
import Graphics.XHB.Monad.Internal.Instances.Res
import Graphics.XHB.Monad.Internal.Instances.ScreenSaver
import Graphics.XHB.Monad.Internal.Instances.Shape
import Graphics.XHB.Monad.Internal.Instances.Shm
import Graphics.XHB.Monad.Internal.Instances.Sync
import Graphics.XHB.Monad.Internal.Instances.XCMisc
import Graphics.XHB.Monad.Internal.Instances.Xevie
import Graphics.XHB.Monad.Internal.Instances.XF86Dri
import Graphics.XHB.Monad.Internal.Instances.XFixes
import Graphics.XHB.Monad.Internal.Instances.Xinerama
import Graphics.XHB.Monad.Internal.Instances.Input
import Graphics.XHB.Monad.Internal.Instances.XPrint
import Graphics.XHB.Monad.Internal.Instances.Xproto
import Graphics.XHB.Monad.Internal.Instances.SELinux
import Graphics.XHB.Monad.Internal.Instances.Test
import Graphics.XHB.Monad.Internal.Instances.XvMC
import Graphics.XHB.Monad.Internal.Instances.Xv